name: cash_vic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  introduction_screen: ^3.0.2
  pin_code_fields: ^7.4.0
  flutter_switch: ^0.3.2
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  flutter_staggered_grid_view: ^0.6.1
  fluttertoast: ^8.0.9
  get_storage: ^2.0.3
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  build_runner: ^2.2.0
  intl: ^0.17.0
  flutter_fortune_wheel: ^1.2.0
  clipboard: ^0.1.3
  share_plus: ^4.0.10+1
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/intro_images/
    - assets/sign_up/
    - assets/home_images/
    - assets/drawer_images/
